using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace WindowsFormsApplication4.Const
{
    class Employee_Prop
    {
        public const string Cashier_ID = "Cashier_ID";
        public const string CustNum = "CustNum";
        public const string Dept_ID = "Dept_ID";
        public const string Password = "Password";
        public const string Swipe_ID = "Swipe_ID";
        public const string Hourly_Wage = "Hourly_Wage";
        public const string Form_Color = "Form_Color";
        public const string CDL = "CDL";
        public const string Name = "Name";
        public const string CFA_Setup_Company = "CFA_Setup_Company";
        public const string CFA_Setup_Bonus = "CFA_Setup_Bonus";
        public const string CFA_Setup_Tax = "CFA_Setup_Tax";
        public const string CFA_Setup_Accounting = "CFA_Setup_Accounting";
        public const string CFA_Setup_Discounts = "CFA_Setup_Discounts";
        public const string CFA_Setup_Display = "CFA_Setup_Display";
        public const string CFA_Setup_DefPrinter = "CFA_Setup_DefPrinter";
        public const string CFA_Inven_Add = "CFA_Inven_Add";
        public const string CFA_Inven_Edit = "CFA_Inven_Edit";
        public const string CFA_Vendors_Add = "CFA_Vendors_Add";
        public const string CFA_Vendors_Edit = "CFA_Vendors_Edit";
        public const string CFA_Depts_Add = "CFA_Depts_Add";
        public const string CFA_Depts_Edit = "CFA_Depts_Edit";
        public const string CFA_Inven_TickVouch = "CFA_Inven_TickVouch";
        public const string CFA_Cust_add = "CFA_Cust_add";
        public const string CFA_Cust_Edit = "CFA_Cust_Edit";
        public const string CFA_Reports_Display = "CFA_Reports_Display";
        public const string CFA_Reports_DDR = "CFA_Reports_DDR";
        public const string CFA_Reports_Print = "CFA_Reports_Print";
        public const string CFA_Invoice_Discount = "CFA_Invoice_Discount";
        public const string CFA_Invoice_PriceChange = "CFA_Invoice_PriceChange";
        public const string CFA_Invoice_DeleteItems = "CFA_Invoice_DeleteItems";
        public const string CFA_Invoice_Void = "CFA_Invoice_Void";
        public const string CFA_CRE_Acct = "CFA_CRE_Acct";
        public const string CFA_CRE_Exit = "CFA_CRE_Exit";
        public const string Dirty = "Dirty";
        public const string Last_DDR = "Last_DDR";
        public const string CFA_Display_Balance = "CFA_Display_Balance";
        public const string CFA_Refund_Item = "CFA_Refund_Item";
        public const string Disp_Pay_Option = "Disp_Pay_Option";
        public const string Disp_Item_Option = "Disp_Item_Option";
        public const string EmpName = "EmpName";
        public const string CFA_Receive_Items = "CFA_Receive_Items";
        public const string CFA_DO_POS = "CFA_DO_POS";
        public const string CFA_INSTANT_POS = "CFA_INSTANT_POS";
        public const string Section_ID = "Section_ID";
        public const string CFA_Other_Tables = "CFA_Other_Tables";
        public const string CFA_Accept_Cash = "CFA_Accept_Cash";
        public const string CFA_TRANSFER_NOSWIPE = "CFA_TRANSFER_NOSWIPE";
        public const string CFA_ADD_CCTIPS = "CFA_ADD_CCTIPS";
        public const string Disabled = "Disabled";
        public const string Admin_Access = "Admin_Access";
        public const string CFA_PRINT_HOLD = "CFA_PRINT_HOLD";
        public const string CFA_Open_Cash_Drawer = "CFA_Open_Cash_Drawer";
        public const string CCTipsNow = "CCTipsNow";
        public const string ReqClockIn = "ReqClockIn";
        public const string CFA_Split_Checks = "CFA_Split_Checks";
        public const string CFA_Transfer_Tables = "CFA_Transfer_Tables";
        public const string CFA_Extra_Item = "CFA_Extra_Item";
        public const string CFA_Tax_Exempt = "CFA_Tax_Exempt";
        public const string CFA_GC_Sell = "CFA_GC_Sell";
        public const string CFA_GC_Redeem = "CFA_GC_Redeem";
        public const string CFA_SELL_SPECIAL_ITEM = "CFA_SELL_SPECIAL_ITEM";
        public const string CFA_VENDOR_PAYOUT = "CFA_VENDOR_PAYOUT";
        public const string CFA_APPLY_GRATUITY = "CFA_APPLY_GRATUITY";
        public const string First_Name = "First_Name";
        public const string Middle_Name = "Middle_Name";
        public const string Last_Name = "Last_Name";
        public const string SSN = "SSN";
        public const string Address_1 = "Address_1";
        public const string Address_2 = "Address_2";
        public const string City = "City";
        public const string State = "State";
        public const string Zip_Code = "Zip_Code";
        public const string Phone_1 = "Phone_1";
        public const string EMail = "EMail";
        public const string Birthday = "Birthday";
        public const string Picture = "Picture";
        public const string CFA_BUYBACKS_TRADES = "CFA_BUYBACKS_TRADES";
        public const string CFA_CC_Force = "CFA_CC_Force";
        public const string CFA_CC_Below_Floor = "CFA_CC_Below_Floor";
        public const string Current_Cash = "Current_Cash";
        public const string CFA_Cash_Alerts = "CFA_Cash_Alerts";
        public const string CFA_Cash_Pickup = "CFA_Cash_Pickup";
        public const string CDL_Stations_ID = "CDL_Stations_ID";
        public const string CFA_Issue_Credit_Slip = "CFA_Issue_Credit_Slip";
        public const string CFA_Redeem_Credit_Slip = "CFA_Redeem_Credit_Slip";
        public const string CFA_REFUND_OVERRIDE = "CFA_REFUND_OVERRIDE";
        public const string CFA_DRAWER_TRANSFER = "CFA_DRAWER_TRANSFER";
        public const string CFA_LARGE_PURCHASES = "CFA_LARGE_PURCHASES";
        public const string CFA_AUCTION_PHOTO = "CFA_AUCTION_PHOTO";
        public const string CFA_AUCTION_LISTREDEEM = "CFA_AUCTION_LISTREDEEM";
        public const string CFA_AUCTION_SHIP = "CFA_AUCTION_SHIP";
        public const string CFA_APPROVE_CASHCOUNT = "CFA_APPROVE_CASHCOUNT";
        public const string Orig_Emp_ID = "Orig_Emp_ID";
        public const string Orig_Store_ID = "Orig_Store_ID";
        public const string CD_Name = "CD_Name";
        public const string CFA_APPROVE_OLD_RETURNS = "CFA_APPROVE_OLD_RETURNS";
        public const string CFA_APPROVE_EMERGENCY_CLOCKOUT = "CFA_APPROVE_EMERGENCY_CLOCKOUT";
        public const string TimeWorkedThisPeriod = "TimeWorkedThisPeriod";
        public const string OvertimeThreshold = "OvertimeThreshold";
        public const string CFA_PULLBACK_INVOICE = "CFA_PULLBACK_INVOICE";
        public const string CFA_MANAGE_TIMECLOCK = "CFA_MANAGE_TIMECLOCK";
        public const string CFA_PERFORM_ENDOFDAY = "CFA_PERFORM_ENDOFDAY";
        public const string CFA_HOST_LOGIN = "CFA_HOST_LOGIN";
        public const string CFA_REST_OPENTABS = "CFA_REST_OPENTABS";
        public const string CFA_REST_TAKEOUT = "CFA_REST_TAKEOUT";
        public const string CFA_REST_DELIVERY = "CFA_REST_DELIVERY";
        public const string CFA_INVOICE_DELETESENT = "CFA_INVOICE_DELETESENT";
        public const string CFA_INVEN_VIEW = "CFA_INVEN_VIEW";
        public const string CFA_INVEN_VIEWCOST = "CFA_INVEN_VIEWCOST";
        public const string CFA_INVEN_NEGATIVE_INSTANTPOS = "CFA_INVEN_NEGATIVE_INSTANTPOS";
        public const string CFA_ENDTRANS_CASH = "CFA_ENDTRANS_CASH";
        public const string CFA_ENDTRANS_ACCOUNT = "CFA_ENDTRANS_ACCOUNT";
        public const string CFA_REST_COMP = "CFA_REST_COMP";
        public const string CFA_CH_FORCE = "CFA_CH_FORCE";
        public const string CFA_TS_CONFIG = "CFA_TS_CONFIG";
        public const string CFA_TRANSFER_SERVER = "CFA_TRANSFER_SERVER";
        public const string CFA_BACKUP_DATABASE = "CFA_BACKUP_DATABASE";
        public const string CFA_CREDIT_CARD_SETTLEMENT = "CFA_CREDIT_CARD_SETTLEMENT";
        public const string CFA_KITCHEN_REPRINT = "CFA_KITCHEN_REPRINT";
        public const string CFA_SETUP_RECEIPT_NOTES = "CFA_SETUP_RECEIPT_NOTES";
        public const string CFA_MANAGE_TIMECLOCK_OWNTIME = "CFA_MANAGE_TIMECLOCK_OWNTIME";
        public const string CFA_SETUP_ADD_EMPLOYEES = "CFA_SETUP_ADD_EMPLOYEES";
        public const string CFA_SETUP_EDIT_EMPLOYEES = "CFA_SETUP_EDIT_EMPLOYEES";
        public const string CFA_INVENTORY_PROMOTIONS = "CFA_INVENTORY_PROMOTIONS";
        public const string CFA_INVOICE_DISCOUNTS_BELOW_X = "CFA_INVOICE_DISCOUNTS_BELOW_X";
        public const string CFA_BUYBACKTRADE_ABOVE_SET_AMOUNT = "CFA_BUYBACKTRADE_ABOVE_SET_AMOUNT";
        public const string CFA_REPORTS_VIEW_HISTORICAL_DATA = "CFA_REPORTS_VIEW_HISTORICAL_DATA";
        public const string CFA_INVEN_MISC_FIELD_LOCKDOWN = "CFA_INVEN_MISC_FIELD_LOCKDOWN";


        #region Permission

        public const string PROMPT = "P";
        public const string YES = "Y";
        public const string NO = "N";
        #endregion
    }
}
